### ISSUE TITLE
Please Maintain this App

### ISSUE THREAD

**Issue by pydlv** [LedgerHQ/app-password-manager#25]
Hi Ledger devs, please maintain this app to support the latest firmware as well as Ledger Nano X... (maybe even support it as a Bluetooth keyboard?!) Right now you can't install it on X and others have reported the typing feature not working. Seriously this is a disappointment since Trezor has a working password manager app, and not to mention once you introduce a feature such as a password manager it is imperative that it continues to be usable in the future, since people will be unable to access their accounts otherwise.

**Comment by fti7** [comment]
Write them via the Ledger Support. (I did that today) 
I guess its the only way to get attention here :-(

**Comment by TamtamHero** [comment]
https://github.com/LedgerHQ/app-password-manager/pull/27 
Sorry about the delay !
