### ISSUE TITLE
Support on Ledger Nano X

### ISSUE THREAD

**Issue by juan-sebastian** [LedgerHQ/app-password-manager#26]
Hello,

Now that Ledger Nano X has support for OpenPGP app, this is the only missing pice to completely migrate to the ledger Nano X.

It will be possible to add support to the Nano X, and maybe support bluetooth also?

**Comment by pydlv** [comment]
They're not listening

**Comment by fti7** [comment]
Come on guys, more time for non-coin apps please :-)

**Comment by juan-sebastian** [comment]
Hello,

Any news regarding this, perhaps you could point me in the right direction so I can try to port it my self 🙂

**Comment by TamtamHero** [comment]
Sorry for the delay :|
It's a tricky app to port to Nano X, it's using a custom UI lib + USB mode that has not yet been ported to Nano X SDK.
Porting it is pretty much equal to rewriting it. I agree it's a pity though, we'll try to allocate some time to do it.

**Comment by TamtamHero** [comment]
https://github.com/LedgerHQ/app-password-manager/pull/27 
I haven't done much testing but the rework almost exclusively touch UX so it should work just like before on Linux and MacOS.
Please let me know if there's anything wrong :)

**Comment by pydlv** [comment]
Thanks so much! You're the best
